'''
created by edgard.ramos (ismytv@gmail.com)
generated by alice.bash.v.2203a
sáb 20 ago 2022 10:33:09 -05
'''
from base.libs.table import Table
from base import config as PARAMS
from base.models import Stock


class BStock(Table):
    aMessage = []           # lista de mensajes

    def __init__(self):
        self.TO = Stock
        self.message_tablename = self.TO._meta.verbose_name
        self.aMessage = []

    def get_aTO_toArray(self):
        array = list()
        for oTO in self.aTO:
            array.append(self.get_oTO_toDict(oTO))
        return array
    
    def get_oTO_toDict(self, oTO:Stock):
        # acá se genera diccionario con los atributos a retornar
        return {
            'id':oTO.id,
            'producto':oTO.producto,
            'n_stk_act':oTO.n_stk_act,
        }

    ''' ----------------------
        Métodos personalizados
    '''
    def _set_oTO(self, oTO:Stock, data:list(), mode, request):
        '''
            Personalizar oTO
        '''
        oTO.producto = data['producto']
        oTO.n_stk_act = data['n_stk_act']

        if mode != 'new':
            oTO.user_edit_id = request.user.id
        else:
            oTO.user_created_id = request.user.id
            oTO.license_id = request.user.license_id
        return oTO
    
    def validate(self, data:list()):
        self.aMessage = []
        return True

    def save(self, request, mode, id, data:list()):
        ok = False
        if mode == 'new' :
            oTO = self.TO()
            oTO = self._set_oTO(oTO, data, mode, request)
            ok = self.insert(oTO)
        
        else: # edit
            oTO = self.get(id)
            if oTO == None:
                self.message = f'No se encontro registro con id={id}'
                self.error_code = PARAMS.ErrorCode.not_found
            else:
                oTO = self._set_oTO(oTO, data, mode, request,)
                ok = self.update(oTO)
            
        return ok
    
    def get_all(self, license_id:int=None):
        if license_id == None:
            # self.aTO = self.TO.objects.all().order_by('desc')
            self.aTO = self.TO.objects.all()
        else:
            self.aTO = self.TO.objects.all().filter(license_id=license_id)
        return self.aTO

    def get_by_s_codigo(self, s_codigo):
        try:
            oTO = self.TO.objects.get(producto__s_codigo=s_codigo)
        except self.TO.DoesNotExist:
            oTO = None
        return oTO

