'''
created by edgard.ramos (ismytv@gmail.com)
generated by alice.bash.v.2203a
jue 11 ago 2022 23:23:49 -05
'''
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse

from base.libs.template import Template
from base.libs.listview import ListView
from base import config as PARAMS
from base.business.bcainvdet import BCaInvDet
from base.models import CaInvDet
from base.forms.cainvdet_form import CaInvDetForm
from base.business.blog import BLog


@login_required(login_url='login')
def cainvdet_list(request, id):
    oListView = ListView(CaInvDet)
    oListView.template_container = PARAMS.TemplateContainerMain
    oListView.template = PARAMS.Template.cainvdet_list
    oListView.actions['action_new'] = reverse('cainvdet_form', args=['new', 0])
    oListView.is_disabled_button_add = True
    oListView.set_context()
    
    # send cainvcab.id to filter cainvdet
    # the template save id in a hidden input, then js will do a fetch 
    # of action_refresh with that value
    oListView.data['ca_inv_cab_id'] = id

    # save log
    oBLog = BLog()
    #oBLog.save(request, 'new', 0, {
    #    'modulo': 'cainvdet_list',
    #    'accion': 'list_view',
    #})

    return render(request, oListView.template, context=oListView.context)


@login_required(login_url='login')
def cainvdet_form(request, mode, id):
    url_return = 'cainvdet_list'
    oBModel = BCaInvDet()

    if mode != 'new':
        oTO = oBModel.get(id)
        if oTO == None:
            messages.error(request, f'Error. No se encontraron datos para el id = {id}' )
            return redirect(url_return)
    
    if request.method == 'POST':
        if mode == 'new':
            form = CaInvDetForm(request.POST)
        else:
            form = CaInvDetForm(request.POST, instance=oTO)
        if not form.is_valid():
            messages.error(request, 'Error en ingreso de datos')
        elif not oBModel.save(request, mode, id, form.cleaned_data):
            messages.error(request, oBModel.message)
        else:
            messages.success(request, oBModel.message)
            return redirect(url_return)
    else:
        if mode == 'new':
            form = CaInvDetForm()
        else:
            form = CaInvDetForm(instance=oTO)

    oTemplate = Template(CaInvDet)
    oTemplate.template_container = PARAMS.TemplateContainerMain
    oTemplate.template = PARAMS.Template.cainvdet_form
    oTemplate.set_template_title(mode)
    oTemplate.actions['action_cancel'] = reverse(url_return, args=[id])
    oTemplate.data['mode'] = mode
    oTemplate.data['id'] = id
    oTemplate.form = form
    oTemplate.set_context()

    return render(request, oTemplate.template, context=oTemplate.context)
