# Generated by Django 4.0 on 2022-08-12 01:52

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaInvCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('s_fecha_inicio', models.DateField(default=datetime.datetime.now)),
                ('s_fecha_cierre', models.DateField(blank=True, null=True)),
                ('s_descripcion', models.CharField(max_length=100)),
                ('estado_inventario', models.CharField(choices=[('1', 'Abierto'), ('2', 'Cerrado')], default='1', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaInvDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('s_codigo', models.CharField(max_length=20)),
                ('s_cod_barra', models.CharField(max_length=20, null=True)),
                ('s_descripcion', models.CharField(max_length=100)),
                ('n_stk_act', models.DecimalField(decimal_places=4, max_digits=14)),
                ('s_ubicacion', models.CharField(max_length=10)),
                ('ns_conteo1', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ns_conteo2', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ca_inv_cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cainvcab')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('s_codigo', models.CharField(max_length=15)),
                ('s_nombre_completo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('license_key', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(max_length=40)),
                ('num_licenses', models.IntegerField(default=3)),
                ('user_type', models.CharField(default='A', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('s_codigo', models.CharField(max_length=5)),
                ('s_descripcion', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('s_codigo', models.CharField(max_length=20)),
                ('s_descipcion', models.CharField(max_length=100)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.unidadmedida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaInvDetU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('id_conteo', models.IntegerField()),
                ('s_ubicacion', models.CharField(max_length=10)),
                ('ns_conteo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ca_inv_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cainvdet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cainvdet',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto'),
        ),
        migrations.AddField(
            model_name='cainvdet',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.unidadmedida'),
        ),
        migrations.AddField(
            model_name='cainvcab',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empleado'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('user_type', models.CharField(default='U', max_length=1, null=True)),
                ('image_file', models.ImageField(default='avatar.svg', null=True, upload_to='users/')),
                ('license_id', models.IntegerField(default=1)),
                ('status', models.CharField(default='A', max_length=1)),
                ('modo_apariencia', models.CharField(choices=[('0', 'Claro'), ('1', 'Oscuro')], default='0', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
