# Generated by Django 4.0 on 2022-08-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='s_descipcion',
            new_name='s_descripcion',
        ),
    ]
