# Generated by Django 4.0 on 2022-08-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_s_descipcion_producto_s_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cainvdetu',
            name='ca_inv_det',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cainvdets', to='base.cainvdet'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('n_stk_act', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
