# Generated by Django 4.0 on 2022-08-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_cainvdetu_ca_inv_det_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cainvdet',
            name='s_categoria',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='s_categoria',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
