# Generated by Django 4.0 on 2022-08-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cainvdet_s_categoria_producto_s_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.IntegerField()),
                ('user_created_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_edit_id', models.IntegerField(blank=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='', max_length=1)),
                ('modulo', models.CharField(max_length=40)),
                ('accion', models.CharField(max_length=40)),
                ('detalle', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
