# Generated by Django 4.0 on 2022-08-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='cainvdet',
            name='unidad_medida_s_codigo',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
