'''
created by edgard.ramos (ismytv@gmail.com)
generated by alice.bash.v.2203a
sáb 13 ago 2022 17:38:58 -05
'''
from django import forms
from django.utils.translation import gettext_lazy as _
#from django.core.exceptions import ValidationError
from base.models import CaInvDetU

 
class CaInvDetUForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_data()

    def set_data(self):
        self.fields['s_ubicacion'].widget.attrs['autofocus'] = True

    class Meta:
        model = CaInvDetU
        fields = ['s_ubicacion']

        error_messages = {
            's_ubicacion': {
                'unique': _("Ya existe rubro con esa descripción."),
            },
        }

    def clean(self):
        return super().clean()
    
    def clean_s_ubicacion(self):
        data = self.cleaned_data['s_ubicacion'].strip().upper()
        try:
            reg = CaInvDetU.objects.get(s_ubicacion=data)
            if not self.instance.id or self.instance.id != reg.id:
                raise forms.ValidationError('Ya existe otro registro con esa descripción')
        except CaInvDetU.DoesNotExist:
            pass

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data