'''
created by edgard.ramos (ismytv@gmail.com)
generated by alice.bash.v.2203a
vie 19 ago 2022 16:51:52 -05
'''
from django import forms
from django.utils.translation import gettext_lazy as _
#from django.core.exceptions import ValidationError
from base.models import UnidadMedida

 
class UnidadMedidaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_data()

    def set_data(self):
        self.fields['s_descripcion'].widget.attrs['autofocus'] = True

    class Meta:
        model = UnidadMedida
        fields = ['s_descripcion']

        error_messages = {
            's_descripcion': {
                'unique': _("Ya existe rubro con esa descripción."),
            },
        }

    def clean(self):
        return super().clean()
    
    def clean_s_descripcion(self):
        data = self.cleaned_data['s_descripcion'].strip().upper()
        try:
            reg = UnidadMedida.objects.get(desc=data)
            if not self.instance.id or self.instance.id != reg.id:
                raise forms.ValidationError('Ya existe otro registro con esa descripción')
        except UnidadMedida.DoesNotExist:
            pass

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data